spring.application.name=esti

# ===== derby DB (memory) =====
# spring.datasource.url=jdbc:derby:memory:estimateDB;create=true

# ===== derby DB (file save) =====
spring.datasource.url=jdbc:derby:./data/estimateDB;create=true

# JPA
# ddl-auto : create-drop / update
spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
spring.jpa.database-platform=org.hibernate.dialect.DerbyDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# setting upload file size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.jpa.properties.hibernate.default_schema=APP

# =========================
# Image crawler common
# =========================
app.crawler.image-dir=./uploads/product-images
app.crawler.timeout-ms=15000
app.crawler.user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36

# =========================
# ASTD
# =========================
app.crawler.astd.maker=ASTD
app.crawler.astd.vendor-code=A
app.crawler.astd.base-url=https://www.americanstandard.co.kr
app.crawler.astd.category-url=https://www.americanstandard.co.kr/main/product.do?v_cate1=1

# =========================
# INUS
# =========================
app.crawler.inus.maker=INUS
app.crawler.inus.vendor-code=B
app.crawler.inus.base-url=http://www.inushaus.kr
app.crawler.inus.category-url=http://www.inushaus.kr/product/bList.asp?search_cate=1